version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD:postgres_password
  frontend:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - '3000:3000'
  backend:
      build:
        dockerfile: Dockerfile.dev
        context: ./backend
      volumes:
        - ./backend:/app
      command: reflex -r "\.go$$" -s -- sh -c "go run ./"