version: '3.3'
services:
  frontend:
    image: "leoldding/coin-flip-frontend"
    deploy:
      resources:
        limits:
          memory: 128m
    hostname: frontend
    ports:
      - "3000:3000"
  backend:
    image: "leoldding/coin-flip-backend"
    deploy:
      resources:
        limits:
          memory: 128m
    hostname: backend
    environment:
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT