name: Deploy Coin Flip
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t leoldding/coin-flip-frontend ./frontend
      - run: docker build -t leoldding/coin-flip-backend ./backend

      - run: docker push leoldding/coin-flip-frontend
      - run: docker push leoldding/coin-flip-backend

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: coin-flip
          environment_name: coin-flip-env
          existing_bucket_name: elasticbeanstalk-us-east-1-312810085553
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          wait_for_environment_recovery: 3600
          use_existing_version_if_available: false